apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-server-deployment
  labels:
    app: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: websocket-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: websocket-server
    spec:
      containers:
      - name: websocket-server
        # 저장소 이름이 포함된 정확한 이미지 주소를 사용하세요 (예: lumisia/waffle-websocket:v1)
        image: lumisia/websocket-server:v1
        imagePullPolicy: IfNotPresent  # 이미지 다운로드 허용 설정
        env:
        - name: PORT
          value: "1234"
        - name: HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 1234
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"