name: Lumisia CD (Deploy to Server)

on:
  push:
    branches: [ "main" ] # 메인 브랜치에 푸시될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 도커 허브 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 각 이미지 빌드 및 푸시 (-f 옵션 사용)
      # 빌드 단계에서 태그에 ${{ github.run_number }} 사용
      - name: Build and Push Backend
        run: |
          docker build -t lumisia/waffle-app:v${{ github.run_number }} -f backend.dockerfile .
          docker push lumisia/waffle-app:v${{ github.run_number }}
          docker tag lumisia/waffle-app:v${{ github.run_number }} lumisia/waffle-app:latest
          docker push lumisia/waffle-app:latest

      # 빌드 단계에서 태그에 ${{ github.run_number }} 사용
      - name: Build and Push Websocket
        run: |
          docker build -t lumisia/websocket:v${{ github.run_number }} -f websocket.dockerfile .
          docker push lumisia/websocket:v${{ github.run_number }}
          docker tag lumisia/websocket:v${{ github.run_number }} lumisia/websocket:latest
          docker push lumisia/websocket:latest

      - name: Build and Push Frontend
        run: |
          docker build -t lumisia/frontend:v${{ github.run_number }} -f frontend.dockerfile .
          docker push lumisia/frontend:v${{ github.run_number }}
          docker tag lumisia/frontend:v${{ github.run_number }} lumisia/frontend:latest
          docker push lumisia/frontend:latest
